# Raytracing scene description file.
# Let's see how far we come with a plain YAML file.
#

filename: image.png
width: 100
height: 100

# TODO ML Camera object with particular objects
camera:
  x: 5
  y: 5
  z: 5

lookAt:
  x: 5
  y: 5
  z: 0

# Field of View
fov: 90

lights:
  - !com.mlesniak.raytracer.math.Vector3D
    x: 8
    y: 7
    z: 5

objects:
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFFFF00
    center:
      x: 3
      y: 3
      z: -2
    radius: 0.5
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFF0000
    center:
      x: 5
      y: 7
      z: -3
    radius: 0.25
  - !com.mlesniak.raytracer.scene.Sphere
      color: 0x00FF00
      center:
        x: 5
        y: 5
        z: -2
      radius: 1
  - !com.mlesniak.raytracer.scene.Sphere
      color: 0x0000FF
      center:
        x: 4.25
        y: 4.5
        z: -1
      radius: 0.5

  - !com.mlesniak.raytracer.scene.Plane
      color: 0xFF00FF
      point:
        x: 0
        y: 0
        z: 0
      normal:
        x: 0
        y: 1
        z: 0
