# Raytracing scene description file.
# Let's see how far we come with a plain YAML file.
#

filename: image.png
width: 100
height: 100

# TODO ML Camera object with particular objects
camera:
  x: 5
  y: 5
  z: 5

lookAt:
  x: 5
  y: 5
  z: 0

# Field of View
fov: 45


objects:
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFFFF00
    center:
      x: 3
      y: 3
      z: -2
    radius: 0.5
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFF0000
    center:
      x: 5
      y: 7
      z: -3
    radius: 0.25
  - !com.mlesniak.raytracer.scene.Sphere
      color: 0x00FF00
      center:
        x: 5
        y: 5
        z: -2
      radius: 1
