# Raytracing scene description file.
# Let's see how far we come with a plain YAML file.
#

filename: image.png
width: 300
height: 300

# TODO ML Camera object with particular objects
camera:
  x: 5
  y: 5
  z: 5

lookAt:
  x: 5
  y: 5
  z: 0

#animation:
#  file: src/main/resources/scene/default.js
#  ticks: 24
#  # Duration in ms
#  duration: 1000
#  loop: true

# Field of View
fov: 90

lights:
  - !com.mlesniak.raytracer.math.Vector3D
    x: 8
    y: 8
    z: 5

objects:
  # Yellow sphere
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFFFF00
    center:
      x: 2
      y: 0.5
      z: -9
    radius: 0.5
  # Red sphere
  - !com.mlesniak.raytracer.scene.Sphere
    color: 0xFF0000
    center:
      x: 3
      y: 3
      z: -15
    radius: 3
  # Green sphere
  - !com.mlesniak.raytracer.scene.Sphere
      color: 0x00FF00
      center:
        x: 5
        y: 1
        z: -8
      radius: 1
  # Blue sphere
  - !com.mlesniak.raytracer.scene.Sphere
      color: 0x0000FF
      center:
        x: 9
        y: 2
        z: -10
      radius: 2
  # Plane
  - !com.mlesniak.raytracer.scene.Plane
      color: 0xDDDDDD
      point:
        x: 0
        y: 0
        z: 0
      normal:
        x: 0
        y: 1
        z: 0
